# Generated by Django 2.2.7 on 2019-11-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=5)),
                ('item', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(max_length=5)),
                ('price', models.IntegerField(max_length=20)),
                ('qxp', models.IntegerField(max_length=25)),
                ('check', models.CharField(max_length=2)),
            ],
        ),
    ]
