# Generated by Django 2.2.7 on 2019-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_budget_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_list',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
