# Generated by Django 2.2.7 on 2019-12-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191206_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_list',
            name='state',
            field=models.CharField(default='대기중', max_length=5),
        ),
    ]
